version: "3.9"
services:
  backend:
    build: ./server
    expose:
      - "4000"
    environment:
      - AWS_REGION=${AWS_REGION:-ap-southeast-2}
      - CLIENT_ORIGINS=${CLIENT_ORIGINS:-http://localhost:5173}
    networks:
      - appnet

  frontend:
    build: ./client
    expose:
      - "80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-/api}
      - VITE_AWS_REGION=${VITE_AWS_REGION:-ap-southeast-2}
      - VITE_COGNITO_USER_POOL_ID=${VITE_COGNITO_USER_POOL_ID:-ap-southeast-2_CdVnmKfrW}
      - VITE_COGNITO_CLIENT_ID=${VITE_COGNITO_CLIENT_ID:-11pap5u5svkhr1hgjf934sj0id}
    networks:
      - appnet

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
