version: "3.9"
services:
  backend:
    build: ./server
    ports: ["4000:4000"]
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - PARAMETER_S3_BUCKET=${PARAMETER_S3_BUCKET:-/video-app/prod/s3-bucket}
      - PARAMETER_DYNAMO_TABLE=${PARAMETER_DYNAMO_TABLE:-/video-app/prod/dynamo-table}
      - PARAMETER_REGION=${PARAMETER_REGION:-/video-app/prod/region}
      - SECRETS_TRANSCODE_OPTIONS=${SECRETS_TRANSCODE_OPTIONS:-/video-app/prod/transcode}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
      - CLIENT_ORIGINS=${CLIENT_ORIGINS:-http://localhost:5173}
  frontend:
    build: ./client
    ports: ["80:80"]
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:4000}
      - VITE_AWS_REGION=${AWS_REGION:-us-east-1}
      - VITE_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - VITE_COGNITO_APP_CLIENT_ID=${COGNITO_APP_CLIENT_ID}
